### ISSUE TITLE
Maintenance policy

### ISSUE THREAD

**Issue by 2e0byo** [tamland/python-tidal#162]
We should probably work out some kind of policy for PRs etc.  It needn't be formal and it needn't be set in stone.

Here are a few suggestions:

1. let @tehkillerbee gatekeep everything
 - **pros**: single responsibility
 - **cons**: lots of work
 
 2. get consensus from all three of us for everything
 - **pros**: consensus
 - **cons**: slow
 
 3. do one of the first two for 'serious' changes (changes to the interface, dropping stuff, etc), but merge anything small if it looks good to one of us
 - **pros**: quick
 - **cons**: could end up merging stuff we should have looked at harder
 
 Currently I guess we're on 3?  Which makes sense but e.g. I just pushed to master to fix up the latest PR (and get mypy passing again: not sure what happened there).  Seemed worth doing it quickly, but I guess I could have done it in the PR itself.
 
 Just trying to get a feeling here. If we settle for 3.  we should sketch a few examples of 'serious' and 'non serious' changes.  I'd propose that anything which breaks downstream code or changes a significant part of the interface is 'serious' and everything else is 'small', although we'd have to play it by ear.  I'm not sure what closing #109 qualifies as: OTOH it's a 'serious' decision, OTOH it's been the case de-facto for ages. 
 
 @tehkillerbee @BlackLight thoughts?

**Comment by tehkillerbee** [comment]
@2e0byo Both 1 and 2 is probably not feasible since I'd like to avoid stalling development in case one or all of us are busy IRL.

For PRs by external developers, I think it is good idea to have a reviewer. If we know more about each of us' specialties, we can probably assign the PR to the most suitable developer. Alternatively, all of us will get assigned and the PR will be processed when we have time.

For most changes, I'd like at least 1 approval (other than the developer itself). For very big (breaking) changes, it is probably wise to have a couple (all of us?) looking through.

For smaller improvements done by either one of us, I think it is OK to have a small PR with a description of the changes and merge it into master, review optional. Ideally no push directly to master.

**Comment by 2e0byo** [comment]
I think that makes sense.  I was lazy earlier; should have added the remote and done the fixups on the pr branch*.

I'm up for either approach with reviewing.  ATM I don't have any strong feelings on code style: the api is nice and lots of good work has gone into it, but the implementation could probably use some work in a few places.  Getting mypy passing was great, but I'd like to find the time to trim the typing a bit and maybe change a few things to make typing easier (we can make a lot more of it implicit).  But @arusahni did great work there.

Speciality-wise I guess I know pytest and poetry pretty well, and typing pretty well too.  I've not interacted deeply with the internals of tidal and I think @BlackLight probably has a much better idea of what endpoints actually return.  I fixed the tests up by feel, not by knowing (tidal's) api.

@BlackLight over to you!

*have just done the research and it turns out there's a really easy way.  You probably know this, but I was manually adding the remote/cloning again.  If you have github's command line tool `gh` installed you can just:

```bash
$ gh pr checkout 161
```

Pretty neat.  I guess that stops me being lazy again.

**Comment by 2e0byo** [comment]
I'm alright btw with protecting master and preventing pushing full stop @tehkillerbee if you'd rather.

**Comment by tehkillerbee** [comment]
Sorry I have been silent on this issue due to house renovation.

@2e0byo It looks like we will need @tamland to change the settings, as I am not able to do this.

> gh pr checkout 161

Yes, I like to use this method when testing other peoples' PR.
