### ISSUE TITLE
Include API response on error

### ISSUE THREAD

**Issue by bennetrr** [tamland/python-tidal#168]
It would be nice to have the response from the TIDAL API printed to the console, when the request was not successful.

Example:

Instead of having just

```python
HTTP error on 400
Traceback (most recent call last):
...
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.tidal.com/v1/albums/243809417/items?sessionId=8120ebc8-94dd-4451-941e-6304a372fb72&countryCode=DE&limit=1000&offset=0
```

put the response from the api below:

```python
HTTP error on 400
Traceback (most recent call last):
...
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.tidal.com/v1/albums/243809417/items?sessionId=8120ebc8-94dd-4451-941e-6304a372fb72&countryCode=DE&limit=1000&offset=0

Response from TIDAL
{"status":401,"subStatus":6001,"userMessage":"OAuth access token missing"}
```

**Comment by tehkillerbee** [comment]
Agreed, this would be very helpful.

**Comment by jozefKruszynski** [comment]
This is already there in the debug log. I think that in general the error response text is short enough as to not spam the logs, therefore I would propose simply changing from `log.debug` to `log.warning` as the current log line is.

**Comment by 2e0byo** [comment]
I don't think the error is in the logs: [here](https://github.com/tamland/python-tidal/blob/master/tidalapi/request.py#L98-L100) we debug log only if we don't raise.

I'm not a massive fan of [log-and-throw](https://stackoverflow.com/questions/6639963/why-is-log-and-throw-considered-an-anti-pattern) but if we want to do it here it should be `logger.error` I think, not warning.

We actually already pass the right information up.  The trouble is that there's not much of a consensus in python repls as to how to handle extra information in errors.  Consider:

```python
from requests import get
url = 'https://api.tidal.com/v1/albums/243809417/items?sessionId=8120ebc8-94dd-4451-941e-6304a372fb72&countryCode=DE&limit=1000&offset=0'
r = get(url)
try:
    r.raise_for_status()
except Exception as e:
    print("Got exception", e)
    print("Response was", e.response)
    print("Response json was", e.response.json())
```

This prints:

```python
Got exception 401 Client Error: Unauthorized for url: https://api.tidal.com/v1/albums/243809417/items?sessionId=8120ebc8-94dd-4451-941e-6304a372fb72&countryCode=DE&limit=1000&offset=0
Response was <Response [401]>
Response json was {'status': 401, 'subStatus': 6001, 'userMessage': 'OAuth access token missing'}
```

So the problem is that the exception msg doesn't send you looking for the `.response` property, and `repr` on a `requests.Response` is not very verbose.

Personally I'd leave things as they are: this isn't ideal, but it's nothing special in `python-tidal`: people used to requests know they can get this information from the `.response` in the exception, and whilst I don't think that's ideal at least it's just *one* place.  Whatever we do I think we should stick with this (suboptimal) exception passing for compatibility.  But if the useability problem is bad enough, let's log and throw.

P.S. in this case not even my favourite fix of installing the rich traceback handler helps.  The underlying problem is probably that `.json()` is a method, and no repl worth its salt is going to call methods on exception objects.

**Comment by tehkillerbee** [comment]
I'm torn between leaving as is and adding more info. 

I think  the "Unauthorized for url" can be misleading - especially for new users, as it can be caused by many many different things, including incorrect authentication, missing/removed artist/track/album etc.

**Comment by bennetrr** [comment]
Could you do it as an logger.debug?

**Comment by StageBreak** [comment]
Does the Tidal API export the royalty stream, and is there coding for Soitfy?

**Comment by StageBreak** [comment]
My apologies for any confusion that I may have caused.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
