### ISSUE TITLE
Is there any way to get the users currently playing track?

### ISSUE THREAD

**Issue by richstokes** [tamland/python-tidal#20]

**Comment by morguldir** [comment]
The reason for example spotify has this is because you can control your desktop spotify from the phone app, and for discord integration. TIDAL doesn't do any of this, and at least the desktop application and website never try to fetch information about the current track from an api, everything with the streaming is local.

There might be an api endpoint, but i can't find it. The only option i see is using last.fm integration, and then getting the currently playing track from last.fm.

**Comment by curiousercreative** [comment]
Recommend closing this.

**Comment by tehkillerbee** [comment]
Currently, this does not seem to be possible.
