### ISSUE TITLE
How does does a refresh token last

### ISSUE THREAD

**Issue by yungwarlock** [tamland/python-tidal#79]
Hi everyone,

I am implementing this library server-side, so what I did was to generate the credentials at one time then use till it one day expires.
I want to ask how long does a refresh_token last till it expires then I'll have to regenerate it.
Also is there any way I can do authentication without using the url.

Thank you

**Comment by morguldir** [comment]
It should last until you change your password, and if it expired the library would probably handle it for you.

There isn't really a way to do authentication like that, since all the login methods need you to complete captchas relatively often

You can login from another device and pass the required data to load_oauth_session though, which might be easier in some cases
